// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMqX50YpFhAelDDce3Fts-eeisKp7zq3Y',
    appId: '1:1002730011703:web:edaa0c730dc7700c1213b2',
    messagingSenderId: '1002730011703',
    projectId: 'chat-app-4ae1b',
    authDomain: 'chat-app-4ae1b.firebaseapp.com',
    storageBucket: 'chat-app-4ae1b.appspot.com',
    measurementId: 'G-3237TLS6RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7VzfQd0qvl5K4mAnMqCSRkihMhXIeCgU',
    appId: '1:1002730011703:android:40e5a06b9a8097dd1213b2',
    messagingSenderId: '1002730011703',
    projectId: 'chat-app-4ae1b',
    storageBucket: 'chat-app-4ae1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGwzH_xmy07a31lOeM67UpqR7Afgc51mE',
    appId: '1:1002730011703:ios:26241a4e43e698381213b2',
    messagingSenderId: '1002730011703',
    projectId: 'chat-app-4ae1b',
    storageBucket: 'chat-app-4ae1b.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMqX50YpFhAelDDce3Fts-eeisKp7zq3Y',
    appId: '1:1002730011703:web:4da256d48ff3fdb11213b2',
    messagingSenderId: '1002730011703',
    projectId: 'chat-app-4ae1b',
    authDomain: 'chat-app-4ae1b.firebaseapp.com',
    storageBucket: 'chat-app-4ae1b.appspot.com',
    measurementId: 'G-NQMBV7630M',
  );
}
